### ISSUE TITLE
download_kos.py returns empty fasta files

### ISSUE THREAD

**Issue by fbcorrea** [mdsufz/OrtSuite#1]
The current version of download_kos.py is not downloading the sequences given a list of IDs.
Each fasta file corresponding to a KO is generated but their content is empty.

Command: download_kos -o output_dir/ -k kos.txt -v
Log.: [log.txt](https://github.com/mdsufz/OrtSuite/files/6493715/log.txt)

**Comment by mdsufz** [comment]
Dear Felipe, it is now fixed. Please clone the repository again and try to run the complete pipeline again.

Thanks
