### ISSUE TITLE
User input file explanation

### ISSUE THREAD

**Issue by stefaniamagg** [mdsufz/OrtSuite#2]
The user_input.csv file is not explained and I don't understand the columns in the [example file](https://github.com/mdsufz/OrtSuite/blob/master/examples/OrtAn_Results/Results/test_user_input.csv). Can you explain the columns and how to create this table?

**Comment by mdsufz** [comment]
Hi, the first column refers to the name of the proposed pathway. The second column contains the list of reactions that compose said pathway (please use commas to separate reactions). The third column refers to sets of reactions that need to be present in a single species. The forth column refers to transport reactions that need to be included in the analysis although they were not part of the pathway. Here, each reaction/transport pair must be stated. The third and forth columns are optional. Th
